version: '3.8'

services:
  jupyter:
    build: .
    container_name: jupyter-notebook
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
      - ./notebooks:/home/jovyan/work/notebooks
    environment:
      - JUPYTER_ENABLE_LAB=yes
    command: start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''
    restart: unless-stopped

